os: linux
sudo: required
language: cpp
compiler: gcc

before_install:
  - sudo apt-add-repository -y ppa:roblib/ppa
  - sudo apt-get -qq update
  - lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt542
      && sudo apt-get -qq update
      && sudo apt-get -qq install qt54tools qt54svg qt54webkit qt54script
      ;

before_script:
   - QTDIR="/opt/qt54" PATH="$QTDIR/bin:$PATH"
      && qt54-env.sh
      && qmake
      ;
script:
  - make -j2 -k
notifications:
  email: false
